// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAik-zXFk1sUAYUxWwVStqnLG8JtgaTg1E',
    appId: '1:789988056991:web:92e8fb06f62d29eac267aa',
    messagingSenderId: '789988056991',
    projectId: 'replysense-f4fe3',
    authDomain: 'replysense-f4fe3.firebaseapp.com',
    storageBucket: 'replysense-f4fe3.firebasestorage.app',
    measurementId: 'G-G94W6K4HRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArs9zZaPFScJdxG8_LUhV3uhFtzuMsFB4',
    appId: '1:789988056991:android:ab66a184fb171a8ec267aa',
    messagingSenderId: '789988056991',
    projectId: 'replysense-f4fe3',
    storageBucket: 'replysense-f4fe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYX5LpZiTfZ3HCwYMx1ovZXkz45rpxOrQ',
    appId: '1:789988056991:ios:5cee02986bdac89bc267aa',
    messagingSenderId: '789988056991',
    projectId: 'replysense-f4fe3',
    storageBucket: 'replysense-f4fe3.firebasestorage.app',
    iosBundleId: 'com.example.replysenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYX5LpZiTfZ3HCwYMx1ovZXkz45rpxOrQ',
    appId: '1:789988056991:ios:5cee02986bdac89bc267aa',
    messagingSenderId: '789988056991',
    projectId: 'replysense-f4fe3',
    storageBucket: 'replysense-f4fe3.firebasestorage.app',
    iosBundleId: 'com.example.replysenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAik-zXFk1sUAYUxWwVStqnLG8JtgaTg1E',
    appId: '1:789988056991:web:9daa5d3210ade179c267aa',
    messagingSenderId: '789988056991',
    projectId: 'replysense-f4fe3',
    authDomain: 'replysense-f4fe3.firebaseapp.com',
    storageBucket: 'replysense-f4fe3.firebasestorage.app',
    measurementId: 'G-VKYHF3Z17D',
  );

}